export const interestsOptions = [
  { value: "Tech", label: "Tech" },
  { value: "AI", label: "AI" },
  { value: "Pedagogik", label: "Pedagogik" },
  { value: "Innovation", label: "Innovation" },
  { value: "Elevbeteende", label: "Elevbeteende" },
    { value: "Lärandestrategier", label: "Lärandestrategier" },
    { value: "EdTech", label: "EdTech" },
    { value: "Gamification", label: "Gamification" },
    { value: "Mentorskap", label: "Mentorskap" },
    { value: "Neurovetenskap", label: "Neurovetenskap" },
    { value: "Mindfulness", label: "Mindfulness" },
    { value: "Ledarskap", label: "Ledarskap" },
    { value: "Skolutveckling", label: "Skolutveckling" },
    { value: "Sociala färdigheter", label: "Sociala färdigheter" },
    { value: "Kreativt lärande", label: "Kreativt lärande" },
    { value: "Hållbar utveckling", label: "Hållbar utveckling" },
    { value: "Entreprenörskap", label: "Entreprenörskap" },
    { value: "Projektbaserat lärande", label: "Projektbaserat lärande" },
    { value: "Språk och kommunikation", label: "Språk och kommunikation" },
    { value: "Utomhuspedagogik", label: "Utomhuspedagogik" },
    { value: "Specialpedagogik", label: "Specialpedagogik" },
    { value: "Föräldrasamverkan", label: "Föräldrasamverkan" },
    { value: "Arbetsmiljö", label: "Arbetsmiljö" },
    { value: "Konflikthantering", label: "Konflikthantering" },
    { value: "Skolhälsa och välmående", label: "Skolhälsa och välmående" },
    { value: "Storytelling", label: "Storytelling" },
    { value: "Kritiskt tänkande", label: "Kritiskt tänkande" },
    { value: "Källkritik", label: "Källkritik" },
    { value: "Betyg och bedömning", label: "Betyg och bedömning" },
    { value: "Digitala verktyg", label: "Digitala verktyg" },
    { value: "Arbetsro", label: "Arbetsro" }

];
