// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izjiwoslrfqfzxlkpdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aml3b3NscmZxZnp4bGtwZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3NDgzNTAsImV4cCI6MjA1MTMyNDM1MH0.uuA116mnpEtTI7_wXQOLoxfcIWul8pGUQ1gQ-l0T5tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);